// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjkP5XUumQ9e5UOS2_PngOQsmti27D19g',
    appId: '1:145989393323:web:6910bf23dadd7175d490ee',
    messagingSenderId: '145989393323',
    projectId: 'centalki-staging',
    authDomain: 'centalki-staging.firebaseapp.com',
    storageBucket: 'centalki-staging.appspot.com',
    measurementId: 'G-P8J84QW1GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgOSHDrH2IoFVLDzhkhykjdf8Zy7p00uU',
    appId: '1:145989393323:android:a3fd9e425ea9c941d490ee',
    messagingSenderId: '145989393323',
    projectId: 'centalki-staging',
    storageBucket: 'centalki-staging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdAhW7ojsTFiNDDkuwTU3yH_T80FuSVKg',
    appId: '1:145989393323:ios:f030431d45c62201d490ee',
    messagingSenderId: '145989393323',
    projectId: 'centalki-staging',
    storageBucket: 'centalki-staging.appspot.com',
    iosClientId: '145989393323-aa8m8kqhhjb93opbct6ftl33trmfo8vo.apps.googleusercontent.com',
    iosBundleId: 'com.example.centalki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdAhW7ojsTFiNDDkuwTU3yH_T80FuSVKg',
    appId: '1:145989393323:ios:f030431d45c62201d490ee',
    messagingSenderId: '145989393323',
    projectId: 'centalki-staging',
    storageBucket: 'centalki-staging.appspot.com',
    iosClientId: '145989393323-aa8m8kqhhjb93opbct6ftl33trmfo8vo.apps.googleusercontent.com',
    iosBundleId: 'com.example.centalki',
  );
}
