name: jitsi_meet_wrapper
description: A Flutter wrapper around the official JitsiMeetSDKs. With this package, you can launch Jitsi meetings in a native view.
version: 0.0.6
homepage: https://github.com/saibotma/jitsi_meet_wrapper/tree/main/jitsi_meet_wrapper
repository: https://github.com/saibotma/jitsi_meet_wrapper/tree/main/jitsi_meet_wrapper

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  jitsi_meet_wrapper_platform_interface: ^0.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides:
  jitsi_meet_wrapper_platform_interface:
    path: ../jitsi_meet_wrapper_platform_interface

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: dev.saibotma.jitsi_meet_wrapper
        pluginClass: JitsiMeetWrapperPlugin
      ios:
        pluginClass: JitsiMeetWrapperPlugin
